### ISSUE TITLE
CLASS core confusion

### ISSUE THREAD

**Issue by thesourcerer8** [google/gf180mcu-pdk#105]
## Expected Behavior

I would expect 9t cells to have a different CLASS than 7t cells, since they have a different size and therefore need to be placed in a different grid. E.g. Sky130 is using "unithd" for the high-density cells (similar to 7t) and "unit" for the low-density cells (similar to 9t)
I am not sure, which behaviour is the best way to do it.

## Actual Behavior

Both 9t cells and 7t cells are using CLASS core, which might cause confusion of cells from both libraries are used in a design.

**Comment by RTimothyEdwards** [comment]
"CLASS CORE" is a LEF standard---there are only a handful of keywords that can follow "CLASS".  What you're referring to is the "SITE" specification, e.g.: `SITE GF018hv5v_mcu_sc7` which matches the `SITE` definition in the technology LEF file.

What I'm not so sure about is whether "CORE" in "CLASS CORE" is allowed to be lowercase.  As far as I know, all LEF keywords are uppercase.

**Comment by QuantamHD** [comment]
@RTimothyEdwards the case is technically supposed to be uppercase, but OpenROAD accepts lower case.

**Comment by QuantamHD** [comment]
@thesourcerer8 +1 to @RTimothyEdwards CLASS CORE only signifies the cell type. the `SITE` value is what you're after.

**Comment by RTimothyEdwards** [comment]
Like so many things, I cannot find anywhere in the LEF documentation that says whether LEF/DEF keywords must be uppercase.  It is sort of implied by usage, but as far as I can see, not explicitly stated anywhere (although many tidbits of syntax are buried deeply in obscure corners of the document).

**Comment by QuantamHD** [comment]
@RTimothyEdwards I think it probably makes sense to at some point go back and fix that, but at the end of the day OpenROAD does support the mixed case. Unless there's a tool issue then I think at this point we should fix this a lower priority. Given the other very real issues reported by @thesourcerer8

**Comment by RTimothyEdwards** [comment]
@QuantamHD :  Also, the lowercase `core` comes unchanged from the original GF LEF sources, so it presumably works with all the commercial tools.

**Comment by RTimothyEdwards** [comment]
I think this issue can be closed.  Issues #104 and #106 are the important ones.

**Comment by QuantamHD** [comment]
Agreed
