### ISSUE TITLE
The SRAM should probably be in the `IPs` section and not the `digital` section

### ISSUE THREAD

**Issue by mithro** [google/gf180mcu-pdk#15]
Currently in the documentation, SRAM is found under the `digital` section at https://gf180mcu-pdk.readthedocs.io/en/latest/digital/SRAM/sram.html

However, in this repository the SRAM is found under https://github.com/google/gf180mcu-pdk/tree/main/macros/gf180mcu_fd_ip_sram and the repository is named `gf180mcu_fd_ip_sram`.

**Comment by mohanad0mohamed** [comment]
@mithro @atorkmabrains I think this issue should be closed without merging any pull requests because the latest version of this repository already moved the SRAM docs from `digital` directory to `IPs` directory.

https://github.com/google/gf180mcu-pdk/tree/main/docs/IPs/SRAM
