### ISSUE TITLE
Fix all the warnings produced when building sphinx documentation

### ISSUE THREAD

**Issue by mithro** [google/gf180mcu-pdk#20]
Currently there are a lot of warnings produce when building the sphinx documentation.

These should all be cleaned up and then enable the [`sphinx.fail_on_warning`](https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx-fail-on-warning) option so that new warnings are not introduced.

**Comment by mohanad0mohamed** [comment]
This issue https://github.com/google/gf180mcu-pdk/issues/17 should be merged and closed before these pull requests.
