### ISSUE TITLE
Add documentation about versioning system

### ISSUE THREAD

**Issue by mithro** [google/gf180mcu-pdk#23]
The documentation should include information about how the PDK is versioned.

See related issue at https://github.com/google/open-source-pdks/issues/8

**Comment by mohanad0mohamed** [comment]
Hi @mithro 

There is a file in the documentation which includes information about how the PDK is versioned.

Kindly see the file at : [https://github.com/google/gf180mcu-pdk/blob/main/docs/versioning.rst](https://github.com/google/gf180mcu-pdk/blob/main/docs/versioning.rst)

**Comment by mithro** [comment]
This will be fixed by https://github.com/google/gf180mcu-pdk/pull/24
